### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bbinflokkins** [jellyfish-lsef/swm-bugtracker#11]
when i try to inject to get into Roblox it does not say ready for script to work it just stays there not showing anything

**Comment by ghost** [comment]
Same, I try to inject and it doesn't actually inject.

**Comment by josh163** [comment]
yeah same I inject and open Roblox but doesn't actually inject its bugged

**Comment by josh163** [comment]
fix the issue developers I paid 19$ for this not to work

**Comment by josh163** [comment]
when can the bug be fixed? bc been wait for like a month for it to start working again

**Comment by foxt** [comment]
If this is a reoccurring issue please request help in the Discord.

This bug tracker is for issues with the Script-aware M GUI, not injection
issues.

Thanks

**Comment by josh163** [comment]
I need a phone number so I can't join the discord

**Comment by iSimpPe** [comment]
you can't join discord server as well :(

**Comment by iSimpPe** [comment]
add me and invite me to discord server please i need help 
My Discord username - Shorty#6673
