### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sthulaur4** [jellyfish-lsef/swm-bugtracker#12]
when I try to inject it doesn't work, as ill inject, and then when I go into Roblox it doesn't actually inject.

**Comment by josh163** [comment]
I inject and open Roblox nothing injects its bugged

**Comment by josh163** [comment]
I paid 19$ for something that aint gonna work and that it useless

**Comment by foxt** [comment]
Jellyfish was free software.

If you are referring to Script-Ware M, this can be used independently from
Jellyfish, and is the recommended way to use Script-Ware, as Jellyfish is
no longer in active development

**Comment by foxt** [comment]
Sorry for the previous confusion, Script-Ware M is still in active development. As happens every week, Roblox updates and Script-Ware M needs time to adapt to these changes. Please check in the discord for more information.

**Comment by Shidabood** [comment]
When I press inject and try to join Roblox, Roblox doesn't open at all. When I don't inject anymore Roblox opens instantly. Why is this happening? Please fix it as soon as possible
