### ISSUE TITLE
There's a problem that after I inject scripture Roblox doesn't open and its very annoying its not letting me use my scripts because when script ware is injected it won't open[BUG]

### ISSUE THREAD

**Issue by turtlemurtle123** [jellyfish-lsef/swm-bugtracker#13]
**This bug tracker is to report issues with the SWM GUI, NOT issues with injection. If you agree to this, please remove this line**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Monterey 12.3]
 - Version [e.g. 2.5.5]

**Additional context**

**Comment by turtlemurtle123** [comment]
I need help

**Comment by foxt** [comment]
please read the first line of the issue template text

**Comment by turtlemurtle123** [comment]
its not a problem with injection its roblox not opening
