### ISSUE TITLE
is:issue is:open Every time I inject and open roblox and run scripts it says i'm not injected. I have tried re installing script ware, I have made sure all my browsers are up to date and I have restarted my computer many times.[BUG]

### ISSUE THREAD

**Issue by lexiexgrey** [jellyfish-lsef/swm-bugtracker#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Monterey 12.3]
 - Version [e.g. 2.5.5]

**Additional context**

**Comment by foxt** [comment]
This bug tracker is only for SWM GUI issues, plus, as part of weekly updates for Roblox (usually on Wednesdays or Thursdays), Script-Ware M is unavailable for a few hours.
