### ISSUE TITLE
auto execute dosent work every time i click it it acts like i dident[BUG]

### ISSUE THREAD

**Issue by hgrhytr** [jellyfish-lsef/swm-bugtracker#8]
**This bug tracker is to report issues with the SWM GUI, NOT issues with injection. If you agree to this, please remove this line**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Monterey 12.3]
 - Version [e.g. 2.5.5]

**Additional context**

**Comment by foxt** [comment]
Please fill out the template and reopen, thank you.
