### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heikster23** [jellyfish-lsef/swm-bugtracker#9]
Every time I join a game in Roblox, script ware begins to inject but never actually does. I try to run scripts and it says that I must inject before I can run the scripts.. 
PLEASE HELP

**Comment by foxt** [comment]
This bug tracker is only for SWM GUI issues, plus, as part of weekly updates for Roblox (usually on Wednesdays or Thursdays), Script-Ware M is unavailable for a few hours.
